spring:
  application:
    name: CUSTOMER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: Akkuu@0804
    driver-class-name: com.mysql.cj.jdbc.Driver
    
security:
     jwt:
        secret-key: 0cad094583faeea297d4448c834790feec0ae80c5ea262c807507bd33939c113
        expiration-time: 86400000  # 1 hour in milliseconds

server:
  port: 8080


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
