spring:
  application:
    name: BANK-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: Akkuu@0804
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082